name: CI

on:
  push:
    branches:
      - master-g

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        npm install
      env:
        REACT_APP_APIKey: ${{ secrets.GENIUS_API_KEY }}
        REACT_APP_APISecret: ${{ secrets.MUSIX_API_KEY }}

    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@releases/v3
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: build
